### ISSUE TITLE
Error message not clear when version is not available yet

### ISSUE THREAD

**Issue by alexandremjacques** [mvdwg/ember-cli-updater#19]
Trying to update a project to the latest stable release 2.14.1, I received the following message:

```      Updating package.json
          from v2.14.0
            to v2.14.1

invalid json response body at https://raw.githubusercontent.com/ember-cli/ember-new-output/v2.14.1/package.json reason: Unexpected token : in JSON at position 3
FetchError: invalid json response body at https://raw.githubusercontent.com/ember-cli/ember-new-output/v2.14.1/package.json reason: Unexpected token : in JSON at position 3
    at /home/alexandremjacques/Development/Projects/Ember/facilcrm/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Accessing the indicated URL, I got a 404 (the probable root cause of the error message):

https://raw.githubusercontent.com/ember-cli/ember-new-output/v2.14.1/package.json

**Comment by hidnasio** [comment]
@alexandremjacques thanks for reporting the issue.

We fetch the package.json file from this repo https://github.com/ember-cli/ember-new-output/releases but 2.14.1 is not there yet. We definitely need to improve the error message though.
